Add a DCO checker
Signed-off-by: Edward Evans <edward.evans@consensys.net>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,7 +7,33 @@ executors:
   node_executor:
     docker:
       - image: circleci/node:12.9.0-stretch
+  shell_executor:
+    docker:
+      - image: circleci/buildpack-deps:buster-scm
 jobs:
+  dco:
+    executor: shell_executor
+    steps:
+      - checkout
+      - run:
+          name: check
+          command: |
+            status=0
+            while IFS= read -r -a line; do
+              my_array+=( "$line" )
+              done < <( git branch -r | grep -v origin/HEAD )
+            for branch in "${my_array[@]}"
+            do
+              branch=$(echo "$branch" | xargs)
+              echo "Checking commits in branch $branch for commits missing DCO..."
+              while read -r results; do
+                status=1
+                commit_hash="$(echo "$results" | cut -d' ' -f1)"
+                >&2 echo "$commit_hash is missing Signed-off-by line."
+              done < <(git log "$branch" --no-merges --pretty="%H %ae" --grep 'Signed-off-by' --invert-grep -- )
+            done
+            exit $status
+
   build:
     executor: python_executor
     steps:
@@ -95,6 +121,7 @@ workflows:
   version: 2
   default:
     jobs:
+      - dco
       - build
       - vale
       - markdownlint
